<?php

/**
 * Test class for UrlParser.
 * Generated by PHPUnit on 2013-03-03 at 18:34:58.
 */
class UrlParserTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var UrlParser
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new UrlParser(new UrlTableMySQL);
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
		
	}

	public function testIsDisallow()
	{
		$rawUrl = 'http://www.czxiu.com/cz/default.html';
		$obj = $this->object;

		// allow domain
		$obj->allowDomain('/baidu.com$/');
		$obj->allowDomain('sina.com');
		$this->assertTrue($obj->isDisallow('http://www.qq.com/test.html', $rawUrl));
		$this->assertTrue($obj->isDisallow('http://www.baidu.com.cn/test.html', $rawUrl));
		$this->assertTrue($obj->isDisallow('http://id.czxiu.com/zj/21.html', $rawUrl));
		$this->assertFalse($obj->isDisallow('http://news.sina.com.cn/', $rawUrl));
		$this->assertFalse($obj->isDisallow('http://www.czxiu.com', $rawUrl));

		// disallow domain
		$obj->disallowDomain('weibo.com');
		$obj->disallowDomain('#^t\.#');
		$obj->followExternal();
		$this->assertFalse($obj->isDisallow('http://www.qq.com/test.html', $rawUrl));
		$this->assertFalse($obj->isDisallow('http://www.baidu.com.cn/test.html', $rawUrl));
		$this->assertFalse($obj->isDisallow('http://id.czxiu.com/zj/21.html', $rawUrl));
		$this->assertTrue($obj->isDisallow('http://t.czxiu.com/zj/21.html', $rawUrl));
		$this->assertTrue($obj->isDisallow('http://weibo.com/zj/21.html', $rawUrl));
		$this->assertTrue($obj->isDisallow('http://tt.weibo.com/zj/21.html', $rawUrl));

		// disallow rule
		$obj->disallow('/21.html');
		$obj->disallow('#http://x\.#');
		$obj->disallow('#COM\.CN#i');
		$this->assertFalse($obj->isDisallow('http://tt.weibo2.com/zj/22.html', $rawUrl));
		$this->assertTrue($obj->isDisallow('http://x.czxiu.com/zj/21.html', $rawUrl));
		$this->assertFalse($obj->isDisallow('HTTP://x.czxiu.com/zj/211.html', $rawUrl));
		$this->assertTrue($obj->isDisallow('http://www.xxx.com.cn/test.html', $rawUrl));

		// allow rule
		$this->assertFalse($obj->isDisallow('HTTP://x.czxiu.com/ft/2.html', $rawUrl));
		$obj->allow('/zj');
		$this->assertTrue($obj->isDisallow('HTTP://x.czxiu.com/ft/2.html', $rawUrl));
		$this->assertFalse($obj->isDisallow('HTTP://x.czxiu.com/zj/212.html', $rawUrl));
		$this->assertFalse($obj->isDisallow('HTTP://x.czxiu.com/ZJ/212.jpg2', $rawUrl));
		$this->assertFalse($obj->isDisallow('HTTP://x.czxiu.com/zj2/21.php?xyz=1', $rawUrl));

		// disallow ext (default)
		$this->assertTrue($obj->isDisallow('HTTP://x.czxiu.com/ZJ/21.tar?down=yes&x=1', $rawUrl));
		$this->assertFalse($obj->isDisallow('HTTP://x.czxiu.com/zj/212.html', $rawUrl));
		$obj->allowExt('.tar');
		$obj->disallowExt('.html');
		$this->assertFalse($obj->isDisallow('HTTP://x.czxiu.com/ZJ/21.tar?down=yes&x=1', $rawUrl));
		$this->assertTrue($obj->isDisallow('HTTP://x.czxiu.com/zj/212.html?ok=1', $rawUrl));
	}

	/**
	 * @dataProvider provider
	 */
	public function testResetUrl($input, $output)
	{
		$baseUrl = 'http://www.czxiu.com/cz/default.html';
		$obj = $this->object;
		$this->assertEquals($output, $obj->resetUrl($input, $baseUrl));
	}

	public function provider()
	{
		return array(
			array('', 'http://www.czxiu.com/cz/'),
			array('test.html', 'http://www.czxiu.com/cz/test.html'),
			array('./test.html', 'http://www.czxiu.com/cz/test.html'),
			array('../cz/test.html', 'http://www.czxiu.com/cz/test.html'),
			array('../..//test.html', 'http://www.czxiu.com/test.html'),
			array('diy/test.html', 'http://www.czxiu.com/cz/diy/test.html'),
			array('/diy/test.html', 'http://www.czxiu.com/diy/test.html'),
			array('#', 'http://www.czxiu.com/cz/'),
			array('https://diy.czxiu.com', 'https://diy.czxiu.com/'),
			array('http://diy.czxiu.com/index.php#', 'http://diy.czxiu.com/index.php'),
			array('http://diy.czxiu.com/cz/diy/../index.php#', 'http://diy.czxiu.com/cz/index.php'),
		);
	}
}
